### ISSUE TITLE
Some ideas to your tableone

### ISSUE THREAD

**Issue by psymicha** [dewittpe/qwraps2#40]
Dear Peter,

you did great work. I also was working on a similar function. But my approach is a little different. Instead of separately defining the desired statistics I decided to use keywords to tell the function what statistic to calculate. 
My function is not as flexiblee as your's concerning format of the table. But I implemented a testing feature for comparisons between groups, which is often desired by physicians; the function can calculate estimates for survival objects, and it can calculate estimates for subgroups within the groups defined in invar.

Input for my function are two lists, invar (Independent variables) and depvar (dependent variables).
Invar contains the information for which groups statistics should be calcualted. Depvar contains the data. In the names of the list elements of depvar the desired statistics and keywords are defined.
I implemented keywords for subtitles in the table, statistics for subsets within the groups and definition of multinomial variables (which is necessary for statisticale testing).

The functions does:
1. extracts all arguments and meta-information from the names of depvar
2. build a matrix (Task matrix) that contains the information what to calculate and print in each cell of the results table
3. do for each cell, what is defined in the task matrix
4. return matrix with results, that can be printes with xtable etc.

This call:
```
invar <- list("mtcars"=1) 
depvar <- list("subtitle Miles Per Gallon"=1,
               "MPG, range"=mtcars$mpg,
               "MPG, mean (SD)"=mtcars$mpg,
               "MPG, median (IQR)"=mtcars$mpg,
               "subtitle Cylinders"=1,
               "Cylinders, mean"=mtcars$cyl,
               "4 Cylinders, n (%)"=mtcars$cyl==4,
               "6 Cylinders, n (%)"=mtcars$cyl==6,
               "8 Cylinders, n (%)"=mtcars$cyl==8,
               "subtitle Weight"=1,
               "Weight, range"=mtcars$wt)
desctab(invar=invar,depvar=depvar)
```

results in:
```
            Parameter            mtcars
1    Miles Per Gallon              <NA>
2          MPG, range         10.4-33.9
3      MPG, mean (SD)      20.09 (6.03)
4   MPG, median (IQR) 19.2 (15.42-22.8)
5           Cylinders              <NA>
6     Cylinders, mean              6.19
7  4 Cylinders, n (%)           11 (34)
8  6 Cylinders, n (%)            7 (22)
9  8 Cylinders, n (%)           14 (44)
10             Weight              <NA>
11      Weight, range         1.51-5.42
```

And using the testing Feature:

```
invar <- list("4 Cyls"=mtcars$cyl==4,
              "6 Cyls"=mtcars$cyl==6,
              "8 Cyls"=mtcars$cyl==8)
depvar <- list("subtitle Miles Per Gallon"=1,
               "MPG, mean (SD)"=mtcars$mpg,
               "subtitle Weight"=1,
               "Weight, mean (range)"=mtcars$wt,
               "multinom Transmission, n (%)"=TRUE,
               "Automatic"=mtcars$am==0,
               "multioff Manual"=mtcars$am==1)
desctab(invar=invar,depvar=depvar,test=TRUE)
```
Gives:

```
             Parameter           4 Cyls           6 Cyls        8 Cyls p.value
1     Miles Per Gallon             <NA>             <NA>          <NA>      NA
2       MPG, mean (SD)     26.66 (4.51)     19.74 (1.45)   15.1 (2.56)  0.0000
3               Weight             <NA>             <NA>          <NA>      NA
4 Weight, mean (range) 2.29 (1.51-3.19) 3.12 (2.62-3.46) 4 (3.17-5.42)  0.0000
5  Transmission, n (%)             <NA>             <NA>          <NA>  0.0126
6            Automatic           3 (27)           4 (57)       12 (86)      NA
7               Manual           8 (73)           3 (43)        2 (14)      NA
```

The flexibility of your Approach to define the statistics with separate functions aroused doubts about my Approach. My Approach is too unflexible, but your work inspired me and I have now some ideas how to improve my own function.

Thank you very much for that!

Kind regards!
Micha

**Comment by dewittpe** [comment]
Hi @psymicha ,

Thanks for the note.  Your solution reminds me of the [qwraps::tableone](https://github.com/dewittpe/qwraps/blob/master/R/tableone.R) function I wrote awhile ago.

I've had a few people request that I add some form of testing and p-value reporting to use with `summary_table`.  I might work on this at some later date.

A possible work around right now would be two generate the wanted p-values and then selectively place them in a new column of `qwraps2_summary_table` object.  After all, the `qwraps2_summary_tables` are just matrices with some additional attributes.

I'll leave this issue open as a reminder to work on added testing to the `summary_table`
