### ISSUE TITLE
How to call tab_summary on each column of dataframe?

### ISSUE THREAD

**Issue by yoursdearboy** [dewittpe/qwraps2#53]
Greetings. Thank you for this great package.

I have an issue making a summary table for 30+ variables. It would be tiresome and inconvenient to specify each variable, so I try to automate this. I use sapply like this:
```
spec <- sapply(data %>% select(-id, -i, -strata) %>% colnames,
               function(x) tab_summary(data[[x]]),
               simplify = FALSE)
```
But it doesn't work well because of binding to `data`, so I try to somehow use `with` construction (obviously `with(data, tab_summary(x))` doesn't work).

I successfully used `with(data, tab_summary(get(x)))` in previous versions, but after recent updates it fails when calling `summary_table`:
```
Error in summarise_impl(.data, dots) : Evaluation error: invalid first argument.
```

I think that root of my problem is [this code](https://github.com/dewittpe/qwraps2/blob/master/R/summary_table.R#L186) which induces variable name as `x`, not `x` value. For now, I changed it to use extra argument:

```
tab_summary.factor <- function(x, v = NULL, n_perc_args = list(digits = 0, show_symbol = FALSE), envir = parent.frame()) {
  v <- if (is.null(v)) {
    deparse(substitute(x))
  } else {
    glue("`{v}`")
  }
```

And then use it as follows:
```
spec <- sapply(data %>% select(-id, -i, -strata) %>% colnames,
               function(x) tab_summary(data[[x]], x),
               simplify = FALSE)
```

Do I miss something and there's a better way to do this? I think it's a big issue for large datasets.

Thank you.

**Comment by dewittpe** [comment]
I have added an example to the vignette.  If you install the current version of the package from github you can view the vignette via

    vigenette("summary-statistics", package = "qwraps2")

In general, the solution for your work would likely be as follows.  Please test this on your `data` object and let me know if your issue has been resolved. I don't have access to your `data` object so I can't verify the error or solution.

```r
spec <- sapply(data %>% select(-id, -i, -strata) %>% colnames,
               function(x) eval(substitute(with(data, tab_summary(xx)), list(xx = as.name(x)))),
               simplify = FALSE)
```

**Comment by yoursdearboy** [comment]
Thanks. It works well in most situations. But there's an issue if a column name contains spaces.
Here is example:
```r
data <- data.frame(rnorm(10), rnorm(10), rnorm(10)) %>%
  set_names(c('test', 'var', 'test var'))
spec <- sapply(data %>% colnames,
               function(x) eval(substitute(with(data, tab_summary(xx)), list(xx = as.name(x)))),
               simplify = FALSE)
```

```
 Error in parse(text = x, keep.source = FALSE) : 
  <text>:1:21: unexpected symbol
1: ~ qwraps2_min( test var
```

Again that happens because `deparse(substitute(x))` removes `` from the variable name.

**Comment by dewittpe** [comment]
I think f9d05b4 fixes this issue.

Looking over the code needed to efficiently use `tab_summary` for multiple columns I find that there is a need to vectorize `tab_summary`.  I'll track that feature development in issue #54.

**Comment by dewittpe** [comment]
@yoursdearboy, would you mind looking over the `qsummary` feature and modification for building the summary tables?  Please track comment/issues on #54. Thanks.
