### ISSUE TITLE
Vectorize tab_summary

### ISSUE THREAD

**Issue by dewittpe** [dewittpe/qwraps2#54]
Spurred by the comments in issue #53, the `tab_summary` function should be vectorized to handle multiple variables at a time, instead of the one offs that are currently supported.  

Make sure that the modified code will still work with the code examples in #53 and related commits.

**Comment by yoursdearboy** [comment]
Hi @dewittpe. This is great.

But somehow dropped support of missing values. Check the demo:

```r
data <- mtcars
data$cyl[5] <- NA
summary_table(data)
```

```
Error in summarise_impl(.data, dots) : 
  Evaluation error: missing values and NaN's not allowed if 'na.rm' is FALSE.
```

And note that there's no **Unknown** element in the spec:

```r
qsummary(data)
```

```
$cyl
$cyl$minimum
~qwraps2::frmt(min(.data[["cyl"]]))

$cyl$`median (IQR)`
~qwraps2::median_iqr(.data[["cyl"]])

$cyl$`mean (sd)`
~qwraps2::mean_sd(.data[["cyl"]])

$cyl$maximum
~qwraps2::frmt(max(.data[["cyl"]]))
```

**Comment by yoursdearboy** [comment]
Also, [this](https://github.com/dewittpe/qwraps2/commit/f64950376bd53424cceb7c5866d7ea43ffe7a427#diff-b1eed1a4d1ebb6a71008aff021f4b781R341), [this](https://github.com/dewittpe/qwraps2/commit/f64950376bd53424cceb7c5866d7ea43ffe7a427#diff-b1eed1a4d1ebb6a71008aff021f4b781R373) and [this](https://github.com/dewittpe/qwraps2/commit/f64950376bd53424cceb7c5866d7ea43ffe7a427#diff-b1eed1a4d1ebb6a71008aff021f4b781R302) tables aren't rendered correctly in the vignette.
See [the screenshot](https://imgur.com/a/fdduJoi).

**Comment by dewittpe** [comment]
Thank you, @yoursdearboy, for checking the documentation building new test cases.  I've made edits to the examples, vignette, and the code to handle missing values.  If you could test out these changes I would appreciate it.

```r
library(qwraps2)
temp <- mtcars
temp$cyl[5] <- NA
temp$am[c(1, 5, 10)] <- NA
temp$am <- factor(temp$am, levels = 0:1, labels = c("Automatic", "Manual"))
temp$vs <- as.logical(temp$vs)
temp$vs[c(2, 6)] <- NA
summary_table(dplyr::select(temp, .data$cyl, .data$am, .data$vs))
```


|                          |dplyr::select(temp, .data$cyl, .data$am, .data$vs) (N = 32) |
|:-------------------------|:-----------------------------------------------------------|
|**cyl**                   |&nbsp;&nbsp;                                                |
|&nbsp;&nbsp; minimum      |4.00                                                        |
|&nbsp;&nbsp; median (IQR) |6.00 (4.00, 8.00)                                           |
|&nbsp;&nbsp; mean (sd)    |6.13 &plusmn; 1.78                                          |
|&nbsp;&nbsp; maximum      |8.00                                                        |
|&nbsp;&nbsp; Unknown      |1/32 (3)                                                    |
|**am**                    |&nbsp;&nbsp;                                                |
|&nbsp;&nbsp; Automatic    |17 (59)                                                     |
|&nbsp;&nbsp; Manual       |12 (41)                                                     |
|&nbsp;&nbsp; Unknown      |3/32 (9)                                                    |
|**vs**                    |&nbsp;&nbsp;                                                |
|&nbsp;&nbsp; True         |13 (43)                                                     |
|&nbsp;&nbsp; Unknown      |2/32 (6)                                                    |

**Comment by yoursdearboy** [comment]
Looks good (especially displaying the number of missing values as a separate row). Tested it on my data - works well.
Thank you for the project.
