### ISSUE TITLE
rbind() summary tables

### ISSUE THREAD

**Issue by raheems** [dewittpe/qwraps2#55]
It would be nice to have a feature to be able to combine summary tables row-wise. Here's an example

```r
our_summary1 <-
     list("Miles Per Gallon" =
               list("min" = ~ min(mpg),
                    "max" = ~ max(mpg),
                    "mean (sd)" = ~ qwraps2::mean_sd(mpg)),
          "Displacement" =
               list("min" = ~ min(disp),
                    "max" = ~ max(disp),
                    "mean (sd)" = ~ qwraps2::mean_sd(disp))
     )


our_summary2 <-
     list(
          "Weight (1000 lbs)" =
               list("min" = ~ min(wt),
                    "max" = ~ max(wt),
                    "mean (sd)" = ~ qwraps2::mean_sd(wt)),
          "Forward Gears" =
               list("Three" = ~ qwraps2::n_perc0(gear == 3),
                    "Four"  = ~ qwraps2::n_perc0(gear == 4),
                    "Five"  = ~ qwraps2::n_perc0(gear == 5))
     )

library(qwraps2)
options(qwraps2_markup = "markdown")

tab1 <- summary_table(mtcars, our_summary1)
tab2 <- summary_table(mtcars, our_summary2)

# I want to stack these two tables

rbind(tab1, tab2) # a feature would be nice to have
```

Thank you.

**Comment by dewittpe** [comment]
Thank you, @raheems, for the example.  I'll work on building a `rbind` method for `qwraps2_summary_table` objects.

In the mean time, a work around would be to use `c` on the `our_summary1` and `our_summary2` objects in the `summary_table` call, e.g.,

```r
tab3 <- summary_table(mtcars, c(our_summary1, our_summary2))
tab3

## |                       |mtcars (N = 32)        |
## |:----------------------|:----------------------|
## |**Miles Per Gallon**   |&nbsp;&nbsp;           |
## |&nbsp;&nbsp; min       |10.4                   |
## |&nbsp;&nbsp; max       |33.9                   |
## |&nbsp;&nbsp; mean (sd) |20.09 &plusmn; 6.03    |
## |**Displacement**       |&nbsp;&nbsp;           |
## |&nbsp;&nbsp; min       |71.1                   |
## |&nbsp;&nbsp; max       |472                    |
## |&nbsp;&nbsp; mean (sd) |230.72 &plusmn; 123.94 |
## |**Weight (1000 lbs)**  |&nbsp;&nbsp;           |
## |&nbsp;&nbsp; min       |1.513                  |
## |&nbsp;&nbsp; max       |5.424                  |
## |&nbsp;&nbsp; mean (sd) |3.22 &plusmn; 0.98     |
## |**Forward Gears**      |&nbsp;&nbsp;           |
## |&nbsp;&nbsp; Three     |15 (47)                |
## |&nbsp;&nbsp; Four      |12 (38)                |
## |&nbsp;&nbsp; Five      |5 (16)                 |
```

**Comment by dewittpe** [comment]
@raheems, I've pushed up some changes to the package, including a `rbind` method for `qwraps2_summary_table` objects.

Will you please test these changes and see if you are getting the results you expect?  Thanks.

**Comment by raheems** [comment]
Thanks. Will check and provide feedback.

**Comment by raheems** [comment]
Is it available in the CRAN version or in the github version?

**Comment by dewittpe** [comment]
Github version

```r
devtools::install_github("dewittpe/qwraps2")
```

**Comment by raheems** [comment]
Thanks. Trying to install from github but it fails due to "make" error. This error is perhaps unrelated to your package. 

Getting exactly the same error as reported here
https://github.com/ropensci/osmdata/issues/132

**Comment by dewittpe** [comment]
@raheems, I am unable to reproduced the error.  `devtools::install_github("dewittpe/qwraps2")` has been successful on two Windows machines, one running Windows 7, and the other Windows 10.  Rtools 3.5 with R version 3.5.1 and devtools version 1.13.6.

I've been developing on Debian machine with R 3.5.1 and devtools version 1.13.6.

Have you been able to resolve the error you ran into?

**Comment by raheems** [comment]
Sorry for being later on responding. I am trying this on a mac and having issues there as well. This time its fortran  gcc library that is showing error. I know this is probably unrelated to your package, so I am not posting the error here.

**Comment by raheems** [comment]
Finally I was able to find some time and check the `rbind()` functionality. It works! Thanks for adding the feature. Much appreciated. 

I've applied it to a real project and it worked!

**Comment by dewittpe** [comment]
Thank you for testing.  I'm happy to know the feature is working well.
