### ISSUE TITLE
transpose table output from `summary_table`?

### ISSUE THREAD

**Issue by zhouyisu** [dewittpe/qwraps2#59]
Thanks for creating the package. It's very useful. I have several wide tables. I am wondering if there is any solution to transpose them (swap row/column)? An MWE will be:

```
mtcar_summaries <-
  list("Miles Per Gallon" =
       list("min:"         = ~ min(mpg),
            "mean (sd)"    = ~ qwraps2::mean_sd(mpg, denote_sd = "paren"),
            "median (IQR)" = ~ qwraps2::median_iqr(mpg),
            "max:"         = ~ max(mpg))
       )

summary_table(dplyr::group_by(mtcars, cyl), mtcar_summaries)
summary_table(dplyr::group_by(mtcars, am), mtcar_summaries)

```
For each table the descriptive variable I am interested in is fixed (i.e. `mpg`) and the breakdown is also the same. I'd like to put categories of both `cyl` and `am` to rows. Is that possible?

**Comment by dewittpe** [comment]
The underlying structure of the summary table object is a character matrix. The `t()` function should work for the example you've provided.  See below.

```{r}
options(qwraps2_markup = "markdown")
library(qwraps2)

mtcar_summaries <-
  list("Miles Per Gallon" =
       list("min:"         = ~ min(mpg),
            "mean (sd)"    = ~ qwraps2::mean_sd(mpg, denote_sd = "paren"),
            "median (IQR)" = ~ qwraps2::median_iqr(mpg),
            "max:"         = ~ max(mpg))
       )

tab <- summary_table(dplyr::group_by(mtcars, cyl), mtcar_summaries)
ttab <- t(tab)

tab
```


|                          |cyl: 4 (N = 11)      |cyl: 6 (N = 7)       |cyl: 8 (N = 14)      |
|:-------------------------|:--------------------|:--------------------|:--------------------|
|**Miles Per Gallon**      |&nbsp;&nbsp;         |&nbsp;&nbsp;         |&nbsp;&nbsp;         |
|&nbsp;&nbsp; min:         |21.4                 |17.8                 |10.4                 |
|&nbsp;&nbsp; mean (sd)    |26.66 (4.51)         |19.74 (1.45)         |15.10 (2.56)         |
|&nbsp;&nbsp; median (IQR) |26.00 (22.80, 30.40) |19.70 (18.65, 21.00) |15.20 (14.40, 16.25) |
|&nbsp;&nbsp; max:         |33.9                 |21.4                 |19.2                 |

```{r}
ttab
```


|                             |min:         |mean (sd)    |median (IQR)         |max:         |
|:----------------------------|:------------|:------------|:--------------------|:------------|
|**Miles Per Gallon**         |&nbsp;&nbsp; |&nbsp;&nbsp; |&nbsp;&nbsp;         |&nbsp;&nbsp; |
|&nbsp;&nbsp; cyl: 4 (N = 11) |21.4         |26.66 (4.51) |26.00 (22.80, 30.40) |33.9         |
|&nbsp;&nbsp; cyl: 6 (N = 7)  |17.8         |19.74 (1.45) |19.70 (18.65, 21.00) |21.4         |
|&nbsp;&nbsp; cyl: 8 (N = 14) |10.4         |15.10 (2.56) |15.20 (14.40, 16.25) |19.2         |

@zhouyisu, does `t` work for your situation?

**Comment by zhouyisu** [comment]
Yes, it does the trick @dewittpe . Thanks for the update.
