### ISSUE TITLE
R markdown table does not format at all

### ISSUE THREAD

**Issue by KristenZhao** [dewittpe/qwraps2#69]
the table does not format as a markdown table, but only presents as a text table, very ugly. It's very frustrating because no tutorial seems to address this issue.
`---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plyr) # if it is installed after dplyr, there is problem
library(dplyr)
library(psych)
library(tidyr)
library(ggplot2)
library(gtools)
library(reshape)
library(reshape2)
library(magrittr) # includes the %<>% operator
library(qwraps2) # create tables
library(broom)
library(formattable)
library(summarytools)
Sys.setlocale(category = "LC_ALL", locale = "chinese")
options(scipen = 6)
options(qwraps2_markup = "markdown")
```

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r cars}
data(mtcars)
mtcars
class(mtcars$cyl)
mtcars2<- dplyr::mutate(mtcars,
                       cyl_factor = factor(cyl, 
                                           levels = c(6,4,8),
                                           labels = paste(c(6,4,8), 'cylinders')),
                       cyl_character = paste(cyl, 'cylinders'))
summary(mtcars2)
```

## Including Plots

You can also embed plots, for example:
```{r pressure, echo=FALSE}
our_summary1 <-
  list("Miles Per Gallon" =
         list("min" = ~ min(.data$mpg),
              "max" = ~ max(.data$mpg),
              "mean (sd)" = ~ qwraps2::mean_sd(.data$mpg)),
       "Displacement" =
         list("min" = ~ min(.data$disp),
              "median" = ~ median(.data$disp),
              "max" = ~ max(.data$disp),
              "mean (sd)" = ~ qwraps2::mean_sd(.data$disp)),
       "Weight (1000 lbs)" =
         list("min" = ~ min(.data$wt),
              "max" = ~ max(.data$wt),
              "mean (sd)" = ~ qwraps2::mean_sd(.data$wt)),
       "Forward Gears" =
         list("Three" = ~ qwraps2::n_perc0(.data$gear == 3),
              "Four"  = ~ qwraps2::n_perc0(.data$gear == 4),
              "Five"  = ~ qwraps2::n_perc0(.data$gear == 5))
  )
whole <- summary_table(mtcars2, our_summary1)
whole

new_summary <-
  mtcars2 %>%
  dplyr::select(.data$mpg, .data$cyl_factor, .data$wt) %>%
  qsummary(.,
           numeric_summaries = list("Minimum" = "~ min(%s)",
                                    "Maximum" = "~ max(%s)"),
           n_perc_args = list(digits = 1, show_symbol = TRUE, show_denom = "always"))
mtcars2 %>%
  dplyr::group_by(.data$am) %>%
  summary_table(., new_summary)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.`

**Comment by dewittpe** [comment]
@KristenZhao I suspect the issue you have is a missing `results = "asis"` chunk option in the last chunk listed above.

An example of a .Rmd file that would produce the result I think you are looking for is included in the qwraps2 package.  The vignette `summary-statistics` covers the construction of the tables.  That vignette does not cover the use of [knitr](https://cran.r-project.org/package=knitr).

You can view the vignette via `vignette("summary-statistics", package = "qwraps2")`

You can view the .Rmd file that created this vignette in an active R session via `file.show(system.file("doc/summary-statistics.Rmd", package = "qwraps2"))`

Or you can view the file in the source code in `vignettes/summary-statistics.Rmd`  Pay attention to the knitr chunk options, especially the `results = "asis"` option in the chunks rendering tables.

From [the knitr website](https://yihui.name/knitr/options/#text-results):

> results: ('markup'; character) takes these possible values
> * markup: mark up the results using the output hook, e.g. put results in a special LaTeX environment
> * asis: output as-is, i.e., write raw results from R into the output document
> * hold: hold all the output pieces and push them to the end of a chunk
> * hide (or FALSE): hide results; this option only applies to normal R output (not warnings, messages or errors)
