### ISSUE TITLE
"caption" argument for summary_table for markup?

### ISSUE THREAD

**Issue by adrian-gadient** [dewittpe/qwraps2#70]
I'm writing a paper in R Markdown that I would like to export as PDF. When I add the following arguments, the pdf is exported correclty but doesn't include the caption:
```
caption = "Demographic profile of survey participants" and 
markup = "markdown"
```
I tried to replace "markdown" with "latex" (in the code above), but then I receive the following error message when I try to knitr: 

```
! Misplaced \noalign.
\hline ->\noalign 
                  {\ifnum 0=`}\fi \hrule \@height \arrayrulewidth \futurelet...
l.14 \hline
```
Do you have any suggestions as to how I could add a caption to an R Markdown document that I want to export with knitr to PDF?

**Comment by dewittpe** [comment]
Hi @abruegger, 

The you can pass the `caption` argument via the `print` method for `summary_table`, examples will follow.

I am going to guess at the cause of the issue you have.  If I am wrong, please provide a reproducible example so I can troubleshoot it.

My guess is that somewhere you have `options(qwraps2_markup = 'markdown')` set.  Also, in the construction of the summary table you have the need for a &plusmn; symbol.   As such, when the character matrix is built by `summary_table` the html markup `&plusmn;` will be used.  The print method for summary tables will wrap the contents for the character matrix in either LaTeX or markdown as needed.  This can, and I suspect in your case, cause a conflict.

I have pushed up an example `.Rmd` file to the repo to illustrate this issue.  Please take at look at https://github.com/dewittpe/qwraps2/blob/master/examples/github-issues/qwraps2-issue-0070.Rmd

I suppose the one other note to make is that I built the formatting tools in qwraps2 under the assumption that one of two workflows would take place:

1. .Rmd -> .md -> .html or .docx
2. .Rnw -> .tex -> .pdf

**Comment by adrian-gadient** [comment]
Thanks a lot @dewittpe, I indeed had option set to `qwraps2_markup = 'markdown'`. Changing option to `qwraps2_markup = "latex"` solved the problem that the caption was not displayed. However, while this is now fine, the table isn't formatted nicely anymore, it includes **horizontal lines** above and below every row. 

1) Do you have any suggestions as to how the table can be printed in the standard (nice) format? (My workflow is: R Markdown -> .tex -> .pdf; this is probably why it doesn't look nice.)

2) Or would it be possible to either a) pass the `summary_table` directly to `knitr::kable` or `kableExtra` or b) to pass the result from `print(qwraps2::summary_table, x)` to `knitr::kable` or `kableExtra`? If that were possible, it would probably be easier to get the formatting right. (I tried both a) and b) but couldn't make these approaches work).

Best, Adrian

**Comment by dewittpe** [comment]
@abruegger, try passing `booktabs = TRUE` in the `print` method.  I updated the example .Rmd file to illustrate.  The table looks a lot better with `booktabs = TRUE`.  

The horizontal lines are injected by `knitr::kable` when `format = "latex"` and `booktabs = FALSE`.

**Comment by adrian-gadient** [comment]
`booktabs = TRUE` solved my problem. 

Thanks a lot for this nice package and your support in using it!

**Comment by adrian-gadient** [comment]
I just noted one minor issue: After every 5th row, there is an increased gap between the rows in the final table. Do you have any ideas how to make the table more regular?
![screenshot 2019-02-01 at 07 30 31](https://user-images.githubusercontent.com/31000762/52106484-4798fd00-25f3-11e9-93ac-c6a0fef08564.png)

**Comment by dewittpe** [comment]
That is a really good question.  I don't have any idea what is causing that display issue.  Can you provide a reproducible example so I can try to trouble shoot it?  Cross posting on stackoverflow.com might help too.
