### ISSUE TITLE
Create Tables with Variable Labels

### ISSUE THREAD

**Issue by hectormz** [dewittpe/qwraps2#74]
Is it possible to create tables using the dataframe's variable labels instead of the variable names? This would be useful when using qsummary() to generate automatic/default tables without manually setting variable display names.

**Comment by dewittpe** [comment]
I would expect the answer is yes.  However, before I can give a definitive answer I would like to see a reproducible example of what you are looking for.  My only experience with using variable labels in a data.frame relies on either the [Hmisc](https://cran.r-project.org/package=Hmisc) or setting a attribute "label" for each element of the data frame explicitly.  If you are using some other set up for variable labels I would like to know.

**Comment by hectormz** [comment]
Hi I believe my inspiration for this enhancement came from this usage explained for sjPlot:
https://dmyee.files.wordpress.com/2016/03/table_workshop.pdf
![image](https://user-images.githubusercontent.com/23343812/67992215-163c7480-fbf9-11e9-8ba0-70f62bdd9b36.png)
![image](https://user-images.githubusercontent.com/23343812/67992223-1e94af80-fbf9-11e9-93ec-1ad677bedf63.png)

**Comment by dewittpe** [comment]
@hectormz : I have added to the `qsummary` call to use the `label` attribute, if it exists, on the data frame for building summary tables.  An example as been added to the vignette as well.  The update has been pushed to CRAN for qwraps2 version 0.4.2.

https://cran.r-project.org/web/packages/qwraps2/vignettes/summary-statistics.html#using-variable-labels

**Comment by hectormz** [comment]
@dewittpe awesome! Thank you for the update!
