### ISSUE TITLE
Formatting table with print

### ISSUE THREAD

**Issue by GabiPedra** [dewittpe/qwraps2#76]
Hello,

I am sorry to keep asking things. It is just that I am trying to write a report with a lots of tables and graphs and very new to markdown.

I think would be nice to have some examples of how to format a table using print. I will add some points that I can't find it how to use.

1. Change column width;
2. Change font size;
3. Equivalent repeated_reader function from `knit::kable;`
4. How to interact with `knit::kable`;
5. My table have many rows, how to change font size to fit in the page or to extend to another page?
6. Change position of the table (when I added caption to my table, the position changed)

The example below is just a dummy, where I will have up to 40 responses in my table and some of my summary tables will have twelve columns. 

``` r
library(plyr)
library(dplyr)
library(qwraps2)
options(qwraps2_markup="latex")
library(tidyverse)

## Creating dummy data
group_1<-rep(c("a","b"),5)
group_2<-rep(1:2,each=5)
response_1<-c(1,1,0,0,0,0,0,0,1,0)
response_2<-c(0,1,1,1,1,0,0,0,1,0)
response_3<-c(0,1,0,1,1,1,1,1,1,0)
response_4<-c(0,0,0,0,0,0,0,0,1,0)
response_5<-c(0,0,0,0,0,0,0,0,1,0)
response_6<-c(0,0,0,0,0,0,0,0,1,0)
response_7<-c(0,0,0,0,0,0,0,0,1,0)
response_8<-c(0,0,0,0,0,0,0,0,1,0)
data<-data.frame(group_1,group_2,response_1,response_2,response_3,response_4,response_5,response_6,
                 response_7,response_8)

our_summary1<-list(
  "Responses 1:2"=list("Response 1"=~ qwraps2::n_perc0(response_1 == 1,na_rm = TRUE),
                       "Response 2"=~ qwraps2::n_perc0(response_2 == 1,na_rm = TRUE)),
  "Responses 3:4"=list("Response 3"=~ qwraps2::n_perc0(response_3 == 1,na_rm = TRUE),
                       "Response 4"=~ qwraps2::n_perc0(response_4 == 1,na_rm = TRUE)),
  "Responses 5:6"=list("Response 5"=~ qwraps2::n_perc0(response_5 == 1,na_rm = TRUE),
                       "Response 6"=~ qwraps2::n_perc0(response_6 == 1,na_rm = TRUE)),
  "Responses 7:8"=list("Response 7"=~ qwraps2::n_perc0(response_7 == 1,na_rm = TRUE),
                       "Response 8"=~ qwraps2::n_perc0(response_8 == 1,na_rm = TRUE))
)
all<-summary_table(dplyr::group_by(data,group_1), our_summary1)
sev<-summary_table(dplyr::group_by(data,group_2), our_summary1)
whole<-cbind(sev,all)
print(whole,rtitle="summary", booktabs = TRUE,caption="Example table")
```
Thank you for your help again.

All best,
Gabi
<sup>Created on 2019-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by dewittpe** [comment]
What is your target output?  a .docx file?  a .html file?  there are different solutions for different outputs.  Changing column width or text size are not really markdown options.  A template document for .docx or a .css for the .html files would be the best way to go for these issues.  Take a look at https://bookdown.org/yihui/rmarkdown/word-document.html for details on the reference documents for word documents.

Looking over the example I see you are using LaTeX for the markup language.  Consider using the longtable package for tables requiring more than one page.  Another option is to write in markdown and specify pdf in the output section of the yaml header.  The long tables are usually rendered well.  

As for where the table shows up in the final document, this is an issue with LaTeX.  Without the caption the table is just a tabular environment and renders in place.  With a caption the table is in a float environment and will be moved by LaTeX's rendering engine.  Configuration of the LaTeX preamble might be needed to get the rendering you are looking for.

I'm happy to help, but I will need more details on the specific output and and the look of the documents you are looking for.
