### ISSUE TITLE
Customization of column names in summary_table()

### ISSUE THREAD

**Issue by aipe** [dewittpe/qwraps2#77]
Hi,

I am currently using qwraps2 to create statistics tables for my datasets. I am using the group_by() function on a dataframe to output columns according to the values of an string variable with the following code:
`summary_table(dplyr::group_by(as.data.frame(polluants_stats[[i]]), station), stats_summary)`

This produces the following column names for the table:
`|                    |station: 41B001 (N = 1,440) |station: 41N043 (N = 1,440) |station: 41R001 (N = 1,440) |station: 41R002 (N = 1,440) |station: 41R012 (N = 1,440) |station: 41WOL1 (N = 1,440) |
|:-------------------|:---------------------------|:---------------------------|:---------------------------|:---------------------------|:---------------------------|:---------------------------|`

I have two questions:
1. Is it possible to change these column names to remove 'station: ' and ' (N=...)', please ?
2. Is it possible to reorder the display of these columns according to some given list instead of following their order as they appear in the dataframe, please ?

Many thanks,

Alessandro

**Comment by dewittpe** [comment]
Simple answers to both questions, yes, and yes.

Some examples. First we set up a simple summary table

``` r
library(qwraps2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
options(qwraps2_markup = "markdown") 

my_mtcars <- dplyr::select(mtcars, mpg, cyl, hp)
stats_summary <- list("MPG" =
                      list("min" = ~ qwraps2::frmt(min(.data[["mpg"]])),
                           "max" = ~ qwraps2::frmt(max(.data[["mpg"]]))))

st <- summary_table(dplyr::group_by(my_mtcars, cyl), stats_summary)
```

The default table is

``` r
st
#> 
#> 
#> |                 |cyl: 4 (N = 11) |cyl: 6 (N = 7) |cyl: 8 (N = 14) |
#> |:----------------|:---------------|:--------------|:---------------|
#> |**MPG**          |&nbsp;&nbsp;    |&nbsp;&nbsp;   |&nbsp;&nbsp;    |
#> |&nbsp;&nbsp; min |21.40           |17.80          |10.40           |
#> |&nbsp;&nbsp; max |33.90           |21.40          |19.20           |
```

First question, is it possible to rename the columns, yes. One way is to
define the column names via the `cname` argument of the print method for
the summary table.

``` r
print(st, cname = c("Four Cylinders", "Six", "Eight"))
#> 
#> 
#> |                 |Four Cylinders |Six          |Eight        |
#> |:----------------|:--------------|:------------|:------------|
#> |**MPG**          |&nbsp;&nbsp;   |&nbsp;&nbsp; |&nbsp;&nbsp; |
#> |&nbsp;&nbsp; min |21.40          |17.80        |10.40        |
#> |&nbsp;&nbsp; max |33.90          |21.40        |19.20        |
```

Another way to rename the columns, and one that might be safer in a dynamic
program is to change the column names of the object.
Look at the structure of the `st` object. It is a character matrix and the
column names used by the print method when the cname argument is not
provided.

``` r
str(st)
#>  'qwraps2_summary_table' chr [1:2, 1:3] "21.40" "33.90" "17.80" ...
#>  - attr(*, "dimnames")=List of 2
#>   ..$ : chr [1:2] "min" "max"
#>   ..$ : chr [1:3] "cyl: 4 (N = 11)" "cyl: 6 (N = 7)" "cyl: 8 (N = 14)"
#>  - attr(*, "rgroups")= Named int 2
#>   ..- attr(*, "names")= chr "MPG"
colnames(st)
#> [1] "cyl: 4 (N = 11)" "cyl: 6 (N = 7)"  "cyl: 8 (N = 14)"
colnames(st) <- gsub("cyl", "Cylinders", colnames(st))
colnames(st) <- gsub("\\(.*\\)", "", colnames(st))
st
#> 
#> 
#> |                 |Cylinders: 4  |Cylinders: 6  |Cylinders: 8  |
#> |:----------------|:-------------|:-------------|:-------------|
#> |**MPG**          |&nbsp;&nbsp;  |&nbsp;&nbsp;  |&nbsp;&nbsp;  |
#> |&nbsp;&nbsp; min |21.40         |17.80         |10.40         |
#> |&nbsp;&nbsp; max |33.90         |21.40         |19.20         |
```

Reordering the columns is a little less intuitive right now. Perhaps I
should extend the package features. For now, I would suggest building an
factor in your data frame with the levels set in the order you want the
columns to appear in.

``` r
my_mtcars$my_cyl <- factor(my_mtcars$cyl, levels = c(6, 4, 8), labels = c("Six", "Four", "Eight"))
summary_table(dplyr::group_by(my_mtcars, my_cyl), stats_summary)
#> 
#> 
#> |                 |my_cyl: Six (N = 7) |my_cyl: Four (N = 11) |my_cyl: Eight (N = 14) |
#> |:----------------|:-------------------|:---------------------|:----------------------|
#> |**MPG**          |&nbsp;&nbsp;        |&nbsp;&nbsp;          |&nbsp;&nbsp;           |
#> |&nbsp;&nbsp; min |17.80               |21.40                 |10.40                  |
#> |&nbsp;&nbsp; max |21.40               |33.90                 |19.20                  |

```

<sup>Created on 2019-07-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aipe** [comment]
Hi,

Thanks a lot ! Both worked flawlessly.
