### ISSUE TITLE
Righ-aligned columns in summary_table ?

### ISSUE THREAD

**Issue by aipe** [dewittpe/qwraps2#78]
Hi,

Is there an option for columns from summary_table to be right-aligned, please ?

Thanks,

Alessandro

**Comment by dewittpe** [comment]
Yes, arguments passed through the `print` method go through `qwraps2::qable` and then `knitr::kable`

``` r
library(qwraps2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
options(qwraps2_markup = "markdown")

my_mtcars <- dplyr::select(mtcars, mpg, cyl, hp)
stats_summary <- list("MPG" =
                      list("min" = ~ qwraps2::frmt(min(.data[["mpg"]])),
                           "max" = ~ qwraps2::frmt(max(.data[["mpg"]]))))

st <- summary_table(dplyr::group_by(my_mtcars, cyl), stats_summary)
```

The default table is

``` r
st
#> 
#> 
#> |                 |cyl: 4 (N = 11) |cyl: 6 (N = 7) |cyl: 8 (N = 14) |
#> |:----------------|:---------------|:--------------|:---------------|
#> |**MPG**          |&nbsp;&nbsp;    |&nbsp;&nbsp;   |&nbsp;&nbsp;    |
#> |&nbsp;&nbsp; min |21.40           |17.80          |10.40           |
#> |&nbsp;&nbsp; max |33.90           |21.40          |19.20           |
```

|                 |cyl: 4 (N = 11) |cyl: 6 (N = 7) |cyl: 8 (N = 14) |
|:----------------|:---------------|:--------------|:---------------|
|**MPG**          |&nbsp;&nbsp;    |&nbsp;&nbsp;   |&nbsp;&nbsp;    |
|&nbsp;&nbsp; min |21.40           |17.80          |10.40           |
|&nbsp;&nbsp; max |33.90           |21.40          |19.20           |


``` r
print(st, align = "r")
#> 
#> 
#> |                 | cyl: 4 (N = 11)| cyl: 6 (N = 7)| cyl: 8 (N = 14)|
#> |----------------:|---------------:|--------------:|---------------:|
#> |          **MPG**|    &nbsp;&nbsp;|   &nbsp;&nbsp;|    &nbsp;&nbsp;|
#> | &nbsp;&nbsp; min|           21.40|          17.80|           10.40|
#> | &nbsp;&nbsp; max|           33.90|          21.40|           19.20|
```

|                 | cyl: 4 (N = 11)| cyl: 6 (N = 7)| cyl: 8 (N = 14)|
|----------------:|---------------:|--------------:|---------------:|
|          **MPG**|    &nbsp;&nbsp;|   &nbsp;&nbsp;|    &nbsp;&nbsp;|
| &nbsp;&nbsp; min|           21.40|          17.80|           10.40|
| &nbsp;&nbsp; max|           33.90|          21.40|           19.20|

<sup>Created on 2019-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aipe** [comment]
Thanks !

A.
