### ISSUE TITLE
Implementation questions

### ISSUE THREAD

**Issue by ericpgreen** [dewittpe/qwraps2#83]
@dewittpe please let me know if you'd prefer questions like this be posted to SO or somewhere else.

1. Is there a way to set latex tables to be landscape?

2. Is it possible to show just one level of binary variables? For instance, if I have a variable `Sex` can I report just `Sex: Female` rather than percentages of males and females on two separate lines?

3. Related to #2, is it possible to skip the row-level grouping in these cases so that the row label `Sex: Female` is on the same line as the summary data for this variable (and not with the label on it's own row with white space)?

4. Are captions possible when knitting to PDF? (not `rtitle` style in the table itself)

5. Is it possible to keep the N's when using `cnames` in `print()`?

Great work with qwraps2!

**Comment by dewittpe** [comment]
@ericpgreen The simple answer to all your questions is yes.  Some will require a bit more detail, but what you are looking for can be achieved.  I added the file [qwraps2-issue-0083.Rnw](https://github.com/dewittpe/qwraps2/blob/master/examples/github-issues/qwraps2-issue-0083.Rnw)  and [qwraps2-issue-0083.pdf](https://github.com/dewittpe/qwraps2/blob/master/examples/github-issues/qwraps2-issue-0083.pdf)  to illustrate possible solutions.

**Comment by ericpgreen** [comment]
This is REALLY helpful @dewittpe. Thanks for taking the time to show the possible solutions!!
